inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/DefEndAlignment:
  AutoCorrect: true

Layout/EndAlignment:
  AutoCorrect: true

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/InheritException:
  EnforcedStyle: standard_error

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  AutoCorrect: false

Style/MutableConstant:
  AutoCorrect: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%I': ()
    '%r': ()
    '%w': ()
    '%W': ()

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/UnneededInterpolation:
  AutoCorrect: false
