version: 2

jobs:
  ruby_2.2:
    working_directory: /usr/src/app
    docker:
      - image: ruby:2.2-alpine
    steps:
      - checkout
      - run: apk --update add --no-cache git openssh
      - run: bundle install -j4 --retry=3
      - run: rake build

  ruby_2.3:
    working_directory: /usr/src/app
    docker:
      - image: ruby:2.3-alpine
    steps:
      - checkout
      - run: apk --update add --no-cache git openssh
      - run: bundle install -j4 --retry=3
      - run: rake build

  ruby_2.4:
    working_directory: /usr/src/app
    docker:
      - image: ruby:2.4-alpine
    steps:
      - checkout
      - run: apk --update add --no-cache git openssh
      - run: bundle install -j4 --retry=3
      - run: rake build

  ruby_2.5:
    working_directory: /usr/src/app
    docker:
      - image: ruby:2.5-alpine
    steps:
      - checkout
      - run: apk --update add --no-cache git openssh
      - run: bundle install -j4 --retry=3
      - run: rake build

  ruby_latest:
    working_directory: /usr/src/app
    docker:
      - image: ruby:alpine
    steps:
      - checkout
      - run: apk --update add --no-cache git openssh
      - run: bundle install -j4 --retry=3
      - run: rake build

  deploy:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: create rubygems credentials
          command: |
            mkdir ~/.gem
            echo -e "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
      - run: bundle install -j4 --retry=3
      - run: rake release

workflows:
  version: 2

  workflow:
    jobs:
      - ruby_2.2
      - ruby_2.3
      - ruby_2.4
      - ruby_2.5
      - ruby_latest
      - deploy:
          requires:
            - ruby_2.2
            - ruby_2.3
            - ruby_2.4
            - ruby_2.5
            - ruby_latest
          filters:
            branches:
              only:
                - deploy/production
