version: 2.1

executors:
  ruby:
    parameters:
      version:
        type: string
    docker:
      - image: ruby:<< parameters.version >>
    working_directory: /usr/src/app

jobs:
  test:
    parameters:
      image:
        type: executor
    executor: << parameters.image >>
    steps:
      - run: apk add --no-cache git openssh
      - checkout
      - run: bundle install -j4 --retry=3
      - run: rake build

  release:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: create rubygems credentials
          command: |
            mkdir ~/.gem
            echo -e "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
      - run: bundle install -j4 --retry=3
      - deploy: rake release

workflows:
  workflow:
    jobs:
      - test:
          name: test-ruby_latest
          image:
            name: ruby
            version: alpine
      - test:
          name: test-ruby2.5
          image:
            name: ruby
            version: 2.5-alpine
      - test:
          name: test-ruby2.4
          image:
            name: ruby
            version: 2.4-alpine
      - test:
          name: test-ruby2.3
          image:
            name: ruby
            version: 2.3-alpine
      - test:
          name: test-ruby2.2
          image:
            name: ruby
            version: 2.2-alpine
      - release:
          requires:
            - test-ruby_latest
            - test-ruby2.5
            - test-ruby2.4
            - test-ruby2.3
            - test-ruby2.2
          filters:
            branches:
              only:
                - deploy/production
